feat: add pre-commit hooks
cuducos/minha-receita pull request #166
Opened 2022-11-04 10:28 UTC by willianpaixao

2022-11-08 20:03 UTC, cuducos requested changes
Podemos reverter o `testdata/dados-publicos-cnpj.html` e `testdata/national-treasure.json`? Acredito que foram mudanças involuntárias, mas tento deixar esses arquivos o mais próximo possível dos originais (incluindo caracteres bizarros etc).

2022-11-08 21:18 UTC, willianpaixao commented
Esses arquivos são baixados de outro lugar? Não sabia.
Eles foram modificados pelas hooks que eliminam espaços e tabulações em linhas vazias.

2022-11-08 21:56 UTC, cuducos commented
São. São “fixtures” de onde a gente “raspa” as URL dos arquivos para baixar. Especialmente o HTML é bem bizarro, com erro de sintaxe e já peguei uns caracteres bizarros. Acho bom deixar assim pois aí nos testes nosso _parser_ é testado com algo mais próximo do real possível : )

2022-11-08 22:36 UTC, willianpaixao commented
Ah, tá bom, vou restaurar os arquivos e colocar testdata na lista de ignore.

2023-01-26 18:17 UTC, cuducos commented
Closed by inactivity.

2023-01-26 18:17 UTC, closed without merging