Lê e salva informações da empresa
cuducos/minha-receita pull request #82
Opened 2021-12-22 18:15 UTC by renatosuero

Essa pr depende da #80 , tbm mudei o nome da main(empresa) para evitar confusão com main do go.

2021-12-22 18:37 UTC, renatosuero commented on transform/base_cnpj.go
> +			/*
eu comentei essa linha mas mantive pra falar sobre, aki eu tenho um erro pq temos 2 arquivos de empresa no testdata, ele dá um erro e para a execução, mas nesse caso não é interessante parar,ele poderia continuar e trabalhar o outro, oq acham?

2021-12-22 19:08 UTC, cuducos requested changes
Pq precismaos de um SOCIOSCSV diferente do #80?

2021-12-22 19:08 UTC, cuducos commented on transform/base_cnpj.go
> +func (c *company) fillMain(data []string, l *lookups) error {
Em todo o projeto acho que não usamos _fill_, usamos? Podemos ou usar `add`, ou, como no código que usa tabelas de _look up_, só o nome mesmo. Também, ao invés de `data`, temos usado `r` (de _row_), e normalmente o `lookups` é o primeiro argumento…

```suggestion
func (c *company) mainCNPJ(l *lookus, r []string) error {
```

2021-12-22 19:08 UTC, cuducos commented on transform/base_cnpj.go
> +		return fmt.Errorf("error trying to parse QualificacaoDoResponsavel %s: %w", data[2], err)
```suggestion
		return fmt.Errorf("error trying to parse QualificacaoDoResponsavel %s: %w", data[3], err)
```

2021-12-22 19:08 UTC, cuducos commented on transform/base_cnpj.go
> +		return fmt.Errorf("error trying to parse CapitalSocial %s: %w", data[2], err)
```suggestion
		return fmt.Errorf("error trying to parse CapitalSocial %s: %w", data[4], err)
```

2021-12-22 19:08 UTC, cuducos commented on transform/base_cnpj.go
> +		return fmt.Errorf("error trying to parse EnteFederativoResponsavel%s: %w", data[2], err)
```suggestion
		return fmt.Errorf("error trying to parse EnteFederativoResponsavel%s: %w", data[6], err)
```

2021-12-22 19:08 UTC, cuducos commented on transform/base_cnpj.go
> +	}
Se `c.CodigoNaturezaJuridica` for `nil`, esse bloco ainda funciona? ACHO que sim, mas bom confirmar

2021-12-22 19:08 UTC, cuducos commented on transform/base_cnpj_test.go
> +func TestAddMain(t *testing.T) {
```suggestion
func TestAddBaseCNPJ(t *testing.T) {
```

2021-12-22 19:08 UTC, cuducos commented on transform/base_cnpj_test.go
> +		t.Errorf("expected to error creating a json, got %s", err)
```suggestion
		t.Errorf("expected no error creating a json, got %s", err)
```

2021-12-22 19:08 UTC, cuducos commented on transform/source.go
> +	base_cpnj                 = "EMPRECSV"
No Go usamos _camel case_ ; )

```suggestion
	baseCNPJ                 = "EMPRECSV"
```

2021-12-22 19:16 UTC, cuducos commented on transform/base_cnpj.go
> +			}
Opa, não… esquece… falei besteira aqui.

2021-12-23 11:26 UTC, renatosuero commented
vou fechar essa PR pq voltarei com outra usando o shard que foi criado para o partner, ai acho que é mais fácil pegar uma PR limpinha, oq acham?

2021-12-23 14:54 UTC, cuducos commented
Sinceramente, acho que não precisa fechar não. Dá para refatorar e tal. Se quiser, pareamos nisso.

2021-12-29 01:27 UTC, cuducos commented
Fechado em favor do #89

2021-12-29 01:27 UTC, closed without merging