Add relatorio with database creation and querys
cuducos/minha-receita pull request #98
Opened 2022-01-20 16:26 UTC by feljrz

Criei aqui ou outro _notebook_ com o relatório, baseado em algumas verificações que já foram detectadas como inconsistências, algumas prevalecem e outras foram corrigidas. Adicionei uma forma de criar o banco relacional e realizar as próprias verificações a partir de _querys_ SQL. 

- O relatório está dividido em duas etapas, criação do banco de dados e verificação de inconsistências.
- Vale notar que é necessário a quem estiver realizando a auditoria **colocar todos os arquivos .zip** em uma pasta e indicar o caminho na segunda célula do _notebook_.

2022-01-20 16:57 UTC, cuducos commented
> Criei aqui ou outro notebook com o relatório

Pq criar outro ao invés de dar continuidade no existente? Digo isso pois tentei deixar clara as hipóteses que queremos testar, e ficar com relatórios espalhados torna mais difícil compreender os resultados…

> Adicionei uma forma de criar o banco relacional e realizar as próprias verificações a partir de querys SQL.

Boa. Mas com isso podemos retirar o Dask dos `requirements.txt`, né?

2022-01-20 17:14 UTC, cuducos requested changes
Eu fui revisando e achei o código muito vebroso… fui adicionando uns comentários para tentar melhorar a legibilidade dele e conseguir entender melhor a intenção…

Não tive tempo de ir além da célula 10, mas deixo de dica para todo o resto!

Me diga o que acha desses comentários e com prefere seguir… ok? Muuuuito obrigado — achei sensacional a ideia de usar um SQLite de suporte! Muito simples e efetivo!

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "import pandas as pd\n",
Que tal organizar um pouco isso? A PEP8 sugere `import …` vir antes de `from … import …` e separar nativos, terceiros e próprios da aplicação:

```suggestion
    "import os\n",
    "import sys\n",
    "import zipfile\n",
    "from collections.abc import Mapping, Iterable, Generator\n",
    "from datetime import datetime\n",
    "from io import BytesIO\n",
    "from pathlib import Path\n",
    "from typing import Any\n",
    "import re\n",
    "import sqlite3\n",
    "\n",
    "import pandas as pd\n",
```

E precisamos mesmo do `typing` num notebook como esse?

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "base_path = Path(curr_folder).resolve().parent\n",
Pq misturar `os.path` e `pathlib.Path` ? Podemos padronizar e sempre usar o mais moderno, `pathlib.Path`?

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "# Defina o Path para os .zip disponibilizados pela Receita Federal\n",
Isso pode ser uma célular de texto?

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "    zip_path = os.path.join(base_path, \"data\")"
Qual o sentido dessa lógica?

1. Definir `zip_path` como `None`
2. Verificar se `zip_path` é `None` (ele sempre será, pois vc acabou de definir que ele é igual a `None`)
3. Se for, mudar o valor de `zip_path`

Pq não assim?

```suggestion
    "zip_path = base_path / \"data\""
```

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "pd_i64_t = pd.Int64Dtype()\n",
Podemos não usar essas variáveis, usar direto `pd.…Dtype()` no bloco? Não vejo tanto ganho em digitação, mas a leitura fica pior (tenho que voltar par aver exatamente o que cada variável significa, enquanto os tipos nativos do Pandas já são mais conhecidos na comunidade).

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    ") -> Iterable[pd.DataFrame]:\n",
Pq tipagem só aqui? Podemos tocar sem, o Mypy não vai nos ajudar aqui, vai?

```suggestion
    "def open_zip(file_path, dtype, sep=\";\"):\n",
```

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "        database = file_path.split(\"/\")[-1][:-4]\n",
Usar `Path` para ficar mais fácil de entender:

```suggestion
    "        database = Path(file_path).suffix",
```

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "        print(\"Processing {} data\".format(database))\n",
f-strings facilitam a leitura:

```suggestion
    "        print(\s"Processing {database} data\")\n",
```

2022-01-20 17:14 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "    rexp = re.compile(rf\"{rexp_str}\", re.IGNORECASE)\n",
Não faz sentido compilar a regex a cada chamada na função, podemos mover isso apra fora do bloco da função, como uma constante.

2022-01-20 18:13 UTC, cuducos commented
Outra ideia que tive aqui (obrigado ☕ ! hahaha…)

Fazer um script separado (algo como `contrib/load_data.py`) que carrega os dados no SQLite, e reservamos o notebook apenas para o relatório — acho que isso facilita o desenvolvimento (escrever o script num editor de código com ferramentas e tal) e deixa mais clara as conclusões…

O que acha?

2022-01-21 19:49 UTC, feljrz commented
> Pq criar outro ao invés de dar continuidade no existente? Digo isso pois tentei deixar clara as hipóteses que queremos testar, e ficar com relatórios espalhados torna mais difícil compreender os resultados…
Sim a ideia é unificar. Criei outro, pois estava desenvolvendo localmente acabei não vendo este que você tinha feito e para não polui-lo fiz o PR inicial em outro notebook. 

> Boa. Mas com isso podemos retirar o Dask dos `requirements.txt`, né?
Sim.

2022-01-21 19:56 UTC, feljrz commented on contrib/relatorio.ipynb
> +    "# Defina o Path para os .zip disponibilizados pela Receita Federal\n",
Na verdade a minha ideia seria deixar esta `zip_path` como argumento de linha de comando para o `contrib/load_data.py` , seguindo na sua ideia de construção do banco de dados separado do relatório

2022-01-21 20:03 UTC, cuducos commented on contrib/relatorio.ipynb
> +    "    zip_path = os.path.join(base_path, \"data\")"
Sim, boa!

2022-01-21 20:10 UTC, feljrz commented on contrib/relatorio.ipynb
> +    ") -> Iterable[pd.DataFrame]:\n",
Utilizei por costume mesmo, mas creio que facilita a manutenção. Porém como será apenas um script para a construção do banco de dados pode não haver necessidade

2022-01-21 20:11 UTC, feljrz commented on contrib/relatorio.ipynb
> +    "    rexp = re.compile(rf\"{rexp_str}\", re.IGNORECASE)\n",
Concordo.

2022-01-21 20:13 UTC, feljrz commented
> Fazer um script separado (algo como `contrib/load_data.py`) que carrega os dados no SQLite, e reservamos o notebook apenas para o relatório.

Excelente sugestão irei implementar e muito obrigado pelas outras sugestões agregaram com conhecimentos que não possuia

2022-01-21 20:19 UTC, cuducos commented
Que bom 💜 
Eu ia tentar rodar o notebook esse final de semana, mas de repente, espero a nova versão então : )
Por curiosidade: quanto tempo demora para carregar o SQLite?
**Caso** tu tenha um `.sqlite` pronto, quer compartilhar para facilitar a vida de quem quer seguir o assunto? Qq coisa, me procura no Telegram (mesma arroba que aqui).
Muuuuito obrigado

2022-01-21 21:12 UTC, feljrz commented
>  Por curiosidade: quanto tempo demora para carregar o SQLite? 

Na minha máquina foi cerca de 1h30. Experimentei multi-thread, mas gerou algumas inconsistências na escrita mesmo eu gerenciando o Lock tenho convicção que é possível eu que estou cometendo algum erro.

> **Caso** tu tenha um `.sqlite` pronto, quer compartilhar para facilitar a vida de quem quer seguir o assunto? 

Tenho sim, só preciso pensar num lugar para disponibiliza-lo, pois são mais de 20GB, se tiver alguma sugestão

É muito gratificante poder contribuir :green_heart:

2022-01-21 21:19 UTC, cuducos commented
> Tenho sim, só preciso pensar num lugar para disponibiliza-lo, pois são mais de 20GB, se tiver alguma sugestão

Me manda uma DM no Telegram (mesmo arroba) ou email (meu usuário arroba GMail ponto com) que te mando um link do Dropbox para subir o arquivo ; )

2022-01-21 21:25 UTC, cuducos commented
Ah, @feljrz, sobre o SQLite e concorrência em Python: vi que vc usou o `check_same_thread` como `False` (que parece o certo), mas em alguns momentos faltou esse argumento.

Eu tentaria criar apenas uma conexão (com `check_same_thread=False`) e toda função que depende do SQLite receberia essa mesma conexão como argumento…

2022-01-30 17:46 UTC, closed without merging